### ISSUE TITLE
没有ncmlu.log文件生成

### ISSUE THREAD

**Issue by Lemonawa** [secriy/ncmlu#10]

**Comment by secriy** [comment]
@Lemonawa 如果没有生成 log 文件，可能是没有正确执行程序，或者配置文件出现错误， 请保证配置文件无误且与程序执行目录相同。

**Comment by Lemonawa** [comment]
![Snipaste_2021-09-11_21-07-00](https://user-images.githubusercontent.com/69106050/132948819-32b1a1bd-5f6a-454f-9ac0-4ff9085aeb7a.png)
确认无误了，配置文件直接复制粘贴的

**Comment by secriy** [comment]
@Lemonawa 你好，把注释删掉就可以了。

**Comment by matocool** [comment]
> ![Snipaste_2021-09-11_21-07-00](https://user-images.githubusercontent.com/69106050/132948819-32b1a1bd-5f6a-454f-9ac0-4ff9085aeb7a.png)
> 确认无误了，配置文件直接复制粘贴的

注释一定要删掉，还有密码那个双引号也要删掉！！！！

**Comment by matocool** [comment]
![image](https://user-images.githubusercontent.com/83129369/132955004-c17004ef-16ee-4906-913a-0907beae39ea.png)

**Comment by matocool** [comment]
accounts:
  - phone: 123456
    passwd: 123456
    expired: 2022-09-06
    only_sign: false
-------------------------------------------------------
直接复制分割线上部分，防止错误。~

**Comment by matocool** [comment]
> @Lemonawa 你好，把注释删掉就可以了。

大佬请教下，到期时间。是指这玩意可以挂服务器？开启一次之后，每天都会自动执行吗？

**Comment by secriy** [comment]
@matocool 这个到期时间是应用于批量任务的，程序遇到过期的账号会跳过，和程序执行本身没有关系。

**Comment by matocool** [comment]
> @matocool 这个到期时间是应用于批量任务的，程序遇到过期的账号会跳过，和程序执行本身没有关系。

谢谢大佬~~
