### ISSUE TITLE
好像不行了😂

### ISSUE THREAD

**Issue by kkkkxl** [secriy/ncmlu#19]
今天刚开始还可以登录 就是返回值的是 type 1   登录失败什么的  错误代码是 二百多 记不清了.

现在登录失败了
2022-04-26 22:11:21.4588	ERROR	ncm/ncm.go:51	Post "https://music.163.com/weapi/login/cellphone": context deadline exceeded

**Comment by kkkkxl** [comment]
是的就是i这个问题
ERROR	ncm/ncm.go:74   登录失败: {"loginType":1,"message":"当前登录失败，请稍后再试","code":250}

**Comment by kkkkxl** [comment]
是的就是i这个问题
ERROR	ncm/ncm.go:74   登录失败: {"loginType":1,"message":"当前登录失败，请稍后再试","code":250}

**Comment by zhaoxp520** [comment]
一样，之前用的github action的也登录失败

**Comment by secriy** [comment]
这边应当是网易云音乐方面改了策略，抱歉暂时没有时间修复

**Comment by secriy** [comment]
问题已修复
