### ISSUE TITLE
刷的太快了。。。导致要启动ncmlu好几次。。。

### ISSUE THREAD

**Issue by matocool** [secriy/ncmlu#26]
我先打开个人主页查看累积听歌

然后刷一次，发现只+3

然后我再次启动ncmlu  第二次+13

以此类推，第五次开始就不敢启动了，怕被封IP 封号。。。。

建议加上：：：目前已累计听歌123456首，本次刷至123457首，增加1首

而，设置睡眠和休眠只是针对多账号，

**Comment by matocool** [comment]
同时建议增加，听取自己名下所有的收藏喜欢的音乐。

思路为：随机抽取专辑，歌单，我喜欢 之中的随机曲目。

**Comment by secriy** [comment]
> 我先打开个人主页查看累积听歌
> 
> 然后刷一次，发现只+3
> 
> 然后我再次启动ncmlu 第二次+13
> 
> 以此类推，第五次开始就不敢启动了，怕被封IP 封号。。。。
> 
> 建议加上：：：目前已累计听歌123456首，本次刷至123457首，增加1首
> 
> 而，设置睡眠和休眠只是针对多账号，

就之前的机制来说，刷完之后最多需要等个几十分钟才能看到效果，先观察一下不需要反复刷。另外歌单重复率高，频繁刷是没有用的。
