### ISSUE TITLE
[Bug]登录失败: {"code":-460,"message":"网络太拥挤，请稍候再试！"}

### ISSUE THREAD

**Issue by Initial-heart-1** [secriy/ncmlu#27]
### 问题描述
如题，按文档配置后 cmd 运行 ncmlu，回报此错误。
考虑是网易云的 API 有变动。

### 环境
系统：Windows 10 专业版 x64 21H2 19044.2364
网络：湖南电信 家庭宽带

### 日志
如题。

**Comment by wdssfff00** [comment]
+1🤣
环境
系统：centos7.8
网络：山东电信，公网家宽
