### ISSUE TITLE
[Enhancement]建议保存登录状态

### ISSUE THREAD

**Issue by Initial-heart-1** [secriy/ncmlu#29]
现在每次启动都会执行登录操作以取得凭据，这与正常用户行为显然不同。
测试了一下，凭据的有效期似乎不算短，那么为什么不尝试将它保存下来供以后使用？
~~而且每次登录都发消息私信炸了~~

**Comment by secriy** [comment]
> 现在每次启动都会执行登录操作以取得凭据，这与正常用户行为显然不同。
> 
> 测试了一下，凭据的有效期似乎不算短，那么为什么不尝试将它保存下来供以后使用？
> 
> ~~而且每次登录都发消息私信炸了~~

@Initial-heart-1 简单来说就是没有必要，因为平台目前根本没有这方面的风控。这个脚本通常是用于大量账号执行批量任务，一遍又一遍跑最省事也不用校验Cookie。但凡平台强制要求验证码登录，这个脚本就达不到预期效果了。
