### ISSUE TITLE
改版本可以用云函数执行吗，谢谢

### ISSUE THREAD

**Issue by matocool** [secriy/ncmlu#9]
改版本可以用云函数执行吗，谢谢

**Comment by matocool** [comment]
或者用  GitHub Actions

**Comment by secriy** [comment]
@matocool 你好，云函数版本有旧版的项目支持（gitee）：https://gitee.com/secriy/CloudMusic-LevelUp，根据 GitHub 政策原仓库已经被停用了。ncmlu 项目是用 Go 重写的优化版，主要用于多账号操作，不考虑支持云函数。

**Comment by matocool** [comment]
> @matocool 你好，云函数版本有旧版的项目支持（gitee）：https://gitee.com/secriy/CloudMusic-LevelUp
> 根据 GitHub 政策原仓库已经被停用了。ncmlu 项目是用 Go 重写的优化版，主要用于多账号操作，不考虑支持云函数。

谢谢 大佬~~~
